export const SET_TENANT_COLLECTION = "SET_TENANT_COLLECTION";
export const SET_ALL_COLLECTION = "SET_ALL_COLLECTIONS";
export const SET_TENANT_DISCOUNT = "SET_TENANT_DISCOUNT";
export const SET_ALL_DISCOUNT = "SET_ALL_DISCOUNT";
export const SET_RECEIPT_DATA = "SET_RECEIPT_DATA";
